version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: admin-service-db
    environment:
      POSTGRES_DB: AdminServiceDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - admin-network

  # Admin Service API
  admin-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-service-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AdminServiceDb;Username=admin;Password=admin123
      - JwtSettings__SecretKey=super-secret-key-for-production-use-a-proper-secret-here-with-32-chars
      - JwtSettings__Issuer=AdminService
      - JwtSettings__Audience=AdminServiceAPI
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - admin-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  admin-network:
    driver: bridge
